version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:16.17
    working_directory: ~/test-react-env/react
    steps:
      - checkout:
          path: ~/test-react-env
      - restore_cache:
          keys:
            - node-deps-{{checksum "package-lock.json"}}
      - run:
          name: Install Packages
          command: npm ci
      - save_cache:
          key: node-deps-{{checksum "package-lock.json"}}
          paths:
            - ~/.npm
      - run:
          name: Run Tests
          command: npm run test
      - persist_to_workspace:
          root: ~/test-react-env
          paths:
            - .
  build:
    docker:
      - image: cimg/node:16.17
    working_directory: ~/test-react-env/react
    steps:
      - attach_workspace:
          at: ~/test-react-env
      - run:
          name: 'Build'
          command: npm run build

workflows:
  version: 2
  main:
    jobs:
      - test
      - build:
          requires:
            - test
          filters:
            branches:
              only: master